CREATE TABLE AUDIT_PRODUTO(
pk_aup_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
fk_prd_codigo INT NOT NULL,
aup_prd_nome VARCHAR(50),
aup_prd_descricao VARCHAR(255),
aup_data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY (fk_prd_codigo)
REFERENCES PRODUTO(pk_prd_codigo)
)
